import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Link from "next/link"

export default function Home() {

 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
      <Link href="/register">
        <a >Register</a>
      </Link>
    </div>
  )
}
